### ISSUE TITLE
Decide basic design of the prototype

### ISSUE THREAD

**Issue by franfj** [WaterizeIt/WaterizeIt_HW_Specs#2]
The following decisions have to be made:

* The prototype gets the water from a container, or there's always water in the circuit?
  * In case of using a water container, should we attach a level sensor to it?
* How should the prototype distribute the water? Water pumps? Water electrovalves? Automatized stopcocks?
* Which raspberry PI use?
* How many plants should the prototype be able to water?
* Should we attach humidity sensors to the plants?

Feel free to add more design decisions.

**Comment by jorgechp** [comment]
> The prototype gets the water from a container, or there's always water in the circuit?

In my opinion, we should implement first a container as a water source. This system will be easier than using a tap water one and in case of in the future we decide to implement a tap water system, the upgrade will be less traumatic.

> In case of using a water container, should we attach a level sensor to it?

That can be a good idea and I think we should take in consideration, but not as a prioritary task.

> How should the prototype distribute the water? Water pumps? Water electrovalves? Automatized stopcocks?

In my opinion, we need to choose the cheaper component in terms of price and voltage requirements.

> Which raspberry PI use?

Raspberry Zero Wh

> How many plants should the prototype be able to water?

A minimum of 4 would be nice.

> Should we attach humidity sensors to the plants?

In the very first version of the prototype we should implement just one irrigation factor, that can be determinated by humidity or by time, but just one of them. At the same time, I consider mandatory to design a system that allow us to implement more sensors or irrigation systems in the future without any problem.

**Comment by franfj** [comment]
I agree with you in every point. About the solution for distributing the water, I talked with @mrodort , and we both agree on using water pumps. What do you think?

**Comment by jorgechp** [comment]
After checking pros and cons of water pump vs other water control systems, I'm inclined to use water pumps for the first prototype.


---

Sent by my Apple product at a Starbucks Coffee Shop.

**Comment by franfj** [comment]
Closing...
