### ISSUE TITLE
Draw prototype mock

### ISSUE THREAD

**Issue by franfj** [WaterizeIt/WaterizeIt_HW_Specs#6]
Draw a mock that represents the prototype described in #2.

The following draft can be used as reference:

![waterizedraft](https://user-images.githubusercontent.com/9204198/44896338-2fe1e380-acf8-11e8-9e9f-b3ba304cd926.png)

**Comment by jorgechp** [comment]
Created a new folder, Diagrams.  And added a new diagram with a mocked prototype.
![diagrama1](https://user-images.githubusercontent.com/6136599/44907669-04bbbc00-ad19-11e8-8089-35eac6604a0b.png)
